### ISSUE TITLE
Improve the retrieval of git tags with their dates

### ISSUE THREAD

**Issue by marcwrobel** [endoflife-date/release-data#53]
The current `git` automation retrieves the versions and their dates by checking out repositories to list their tags.

Currently repositories cache is really large (7 GB according to https://github.com/endoflife-date/release-data/actions/runs/3754248949/jobs/6378306154) and takes a lot of time to be fetch (for instance restore on https://github.com/endoflife-date/release-data/actions/runs/3754248949/jobs/6378306154 took more than 3 minutes). And sometime it fails: see https://github.com/endoflife-date/release-data/actions/runs/3753269692/jobs/6376399487.

While looking at a way to reduce the storage needed for git repositories I found https://stackoverflow.com/q/65729722/374236, which propose two way of retrieving on the tags information without a full checkout out of a repository :

- using git (similar but a little bit different than what's currently done)
- using subversion (surprisingly ;))

I think those two methods must be tested against the current method, hopefully they will be better. For the tests lets use https://github.com/quarkusio/quarkus/ because the repository is quite large (both in size and history).

**Comment by marcwrobel** [comment]
Did a quick test with https://github.com/quarkusio/quarkus/, and got those results :

| Method                                                   | Time    | Size | Notes                       |
|----------------------------------------------------------|---------|------|-----------------------------|
| Git (current)                                            | 12.691s | 97M  |                             |
| Git (https://stackoverflow.com/a/65746233/374236)        | 11.864s | 39M  |                             |
| Git (https://stackoverflow.com/a/65746233/374236 + bare) | 8.189s  | 38M  | Same with `git init --bare` |
| SVN (https://stackoverflow.com/a/68445231/374236)        | 11.441  | 0M   |                             |                     |

All methods take a similar time. But the the methods on https://stackoverflow.com/q/65729722/374236 take a lot less space (half for Git, none for SVN). Looks quite promising @captn3m0.

**Comment by captn3m0** [comment]
Our current setup uses `--bare` and a `blob:none` filter. So probably same as the last row?

Ref: https://github.com/endoflife-date/release-data/blob/931657b98f50ae13f6d0e8426b1d0be41884463d/update.rb#L22-L28

I think I'd experimented with svn based pulls as well, but I remember the svn method failing for large repos. Running it on linux repo (33x commits compared to quarkus) for eg, takes 2 minute and fails:

```
time svn --verbose ls https://github.com/gregkh/linux/tags
svn: E170013: Unable to connect to a repository at URL 'https://github.com/gregkh/linux/tags'
svn: E175002: Unexpected HTTP status 504 'Gateway Timeout' on '/gregkh/linux/tags'

real	2m0.362s
user	0m0.038s
sys	0m0.009s
```

A `git` bare filter clone works finishes in 3 minutes. I think for smaller repos, the cost of a fresh svn tag fetch every time is higher than the time for the cache pull (It takes 7.5 seconds using svn v/s 3.5 seconds using no-cache-git-pull for the vue repo for eg).

The cache also makes future fetches (where we just run `git fetch --quiet --tags --filter=blob:none` after populating the cache) quite fast. It takes a second or so on the linux repo. We'd lose this speed advantage, with no cache.

There might be a way for us to optimize the cache size however:

1. ~~By dropping the `pack` data from git (1.5GB of this is just linux repo). Not sure if this will help with keeping future fetch fast.~~ Tested this, it doesn't work.
2. Using separate caches for each project perhaps?

The linux kernel is much of a special case however, the recommended way of using it in CI systems is using a CDN instead: https://kernel.org/best-way-to-do-linux-clones-for-your-ci.html, and having a stable cache (which we don't really, because GitHub Actions).

**Comment by marcwrobel** [comment]
I agree, but we should also consider the retrieval of the cache which is quite long. And we should also consider the fact that the "svn support" on GitHub is something that may be dropped at some point (so better to stick with git IMHO).

> Our current setup uses `--bare` and a `blob:none` filter. So probably same as the last row?

Surprisingly no. I compared the commands used currently in `update.rb` and the commands in https://stackoverflow.com/a/65746233/374236 and the repository size is way lower with the latter.

Here are the commands used in `update.rb` :

```bash
git init --bare linux-eold
cd linux-eold
time git fetch --tags --filter=blob:none https://github.com/gregkh/linux.git
```

Here are the commands used in https://stackoverflow.com/a/65746233/374236 :

```bash
git init --bare linux-so
cd linux-so
git config extensions.partialClone true
git remote add origin https://github.com/gregkh/linux.git
time git fetch --filter=blob:none --tags --depth=1 origin
```

I did the test again this time with linux and here is what I got :

Did a quick test with https://github.com/quarkusio/quarkus/, and got those results :

| Method         | Time      | Size |
|----------------|-----------|------|
| endoflife.date | 4m30.149s | 1.5G |
| Stack Overflow | 0m42.126s | 179M |

I don't know if its due to `extensions.partialClone` or `--depth=1` but it's definitively faster / less space consuming.

**Comment by captn3m0** [comment]
We setup partial clone in the workflow YAML. The depth shouldn’t have any effect. -NemoOn 27-Dec-2022, at 00:35, Marc Wrobel ***@***.***> wrote:﻿
I agree, but we should also consider the retrieval of the cache which is quite long. And we should also consider the fact that the "svn support" on GitHub is something that may be dropped at some point (so better to stick with git IMHO).

Our current setup uses --bare and a blob:none filter. So probably same as the last row?

Surprisingly no. I compared the commands used currently in update.rb and the commands in https://stackoverflow.com/a/65746233/374236 and the repository size is way lower with the latter.
Here are the commands used in update.rb :
git init --bare linux-eold
cd linux-eold
time git fetch --tags --filter=blob:none https://github.com/gregkh/linux.git
Here are the commands used in https://stackoverflow.com/a/65746233/374236 :
git init --bare linux-so
cd linux-so
git config extensions.partialClone true
git remote add origin https://github.com/gregkh/linux.git
time git fetch --filter=blob:none --tags --depth=1 origin
I did the test again this time with linux and here is what I got :
Did a quick test with https://github.com/quarkusio/quarkus/, and got those results :



Method
Time
Size




endoflife.date
4m30.149s
1.5G


Stack Overflow
0m42.126s
179M



I don't know if its due to extensions.partialClone or --depth=1 but it's definitively faster / less space consuming.

**Comment by marcwrobel** [comment]
Just did additional test and it seems `--depth=1` has a big impact on both initial checkout duration (i.e. when cache is empty) and repository size. I suspect it is because a lot of information about git commits don't have to be retrieved and stored.

For those tests I used release-data directly: https://github.com/marcwrobel/release-data-test/ and https://github.com/marcwrobel/release-data-test-2/. In both repositories I removed the _Custom Updates_ and _Commit and update new releases_ steps. And `--depth=1` has been added in the fetch command in https://github.com/marcwrobel/release-data-test-2/. Here are the result :


| Repository         | _Git and DockerHub Update_ duration      | Cache Size |
|----------------|-----------|------|
| [release-data-test](https://github.com/marcwrobel/release-data-test/actions/runs/3785670482/jobs/6435900864) | 11m 1s | 7507 MB |
| [release-data-test-2](https://github.com/marcwrobel/release-data-test-2/actions/runs/3785668382/jobs/6435896689) | 5m 10s | 962 MB |

This is significant for the initial checkout, but also for subsequent run because cache take less than 30s instead of more than 3 mns to be retrieved and extracted.

I will propose a PR that adds the `--depth=1` to the fetch command.

**Comment by captn3m0** [comment]
> "svn support" on GitHub is something that may be dropped at some point

Less than a month later, it now has a sunset date: https://github.blog/2023-01-20-sunsetting-subversion-support/
