### ISSUE TITLE
mvn: dates don't match what's shown on the website.

### ISSUE THREAD

**Issue by captn3m0** [endoflife-date/release-data#61]
See discussion at https://github.com/endoflife-date/endoflife.date/pull/2230#discussion_r1060000800

> Dec 31, 2022 is displayed on [mvnrepository.com/artifact/org.apache.zookeeper/zookeeper/3.6.4](https://mvnrepository.com/artifact/org.apache.zookeeper/zookeeper/3.6.4) (hence my comment). 
> And [mail-archive.com/dev@zookeeper.apache.org/msg75711.html](https://www.mail-archive.com/dev@zookeeper.apache.org/msg75711.html) also display Dec 31, 2022.

But the API returns 18th December:

- https://search.maven.org/solrsearch/select?q=g:org.apache.zookeeper+AND+a:zookeeper&core=gav&rows=1&wt=json&start=%s (1671387029)
- So do the files: https://repo1.maven.org/maven2/org/apache/zookeeper/zookeeper/3.6.4/

Dropped a mail to info@mvnrepository.com, creating this issue to track this properly.

**Comment by marcwrobel** [comment]
@captn3m0, I did not notice before but [mvnrepository.com](mailto:info@mvnrepository.com) are not the one that manage Maven Central. The people that managed Maven Central are Sonatype. And the date is the same between https://repo1.maven.org/maven2/org/apache/zookeeper/zookeeper/3.6.4/ and https://search.maven.org/artifact/org.apache.zookeeper/zookeeper.

I think I may have an explanation about that. Artifacts published on Maven Central are first published to a staging repo ([oss.sonatype.org](https://oss.sonatype.org/)) for verification. Then once the artifacts are validated and ready, then they can be published on Maven Central. It may be a manual process or an automatic process. My guess is that the zookeeper team published the artifacts on the staging repo on 18/12, but only pushed it on Maven Central on 31/12 (maybe because they wanted to validate more things from their side). And mvnrepository.com is aware of the new release only after it is published on Maven Central, so on 31/12, hence the date they provide (they do not use Maven Central's date but the detection date).

If I am right, considering the dates are coherent on Maven Central, I don't think anything can be done.

**Comment by captn3m0** [comment]
Sounds good.

**Comment by captn3m0** [comment]
(Just for confirmation: never got a response back from info@mvnrepository.com)
